###############################################################
#  Generated by:      Cadence Innovus 16.13-s045_1
#  OS:                Linux x86_64(Host ID halle.fransg.eit.lth.se)
#  Generated on:      Tue Feb 27 16:03:12 2024
#  Design:            TOP_with_pads
#  Command:           create_ccopt_clock_tree_spec -file ./ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Clocks present at pin clk_in
#   clk (period 10.000ns) in timing_config Clock_constraints([outputs/TOP_with_pads.sdc])
create_ccopt_clock_tree -name clk -source clk_in -no_skew_group

set_ccopt_property target_max_trans_sdc -delay_corner SS -late -clock_tree clk 0.200
# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -delay_corner SS -late -rise -clock_tree clk 0.500
set_ccopt_property source_latency -delay_corner SS -late -fall -clock_tree clk 0.500
set_ccopt_property source_latency -delay_corner FF -late -rise -clock_tree clk 0.500
set_ccopt_property source_latency -delay_corner FF -late -fall -clock_tree clk 0.500
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk_in 10

# Skew group to balance non generated clock:clk in timing_config:Clock_constraints (sdc outputs/TOP_with_pads.sdc)
create_ccopt_skew_group -name clk/Clock_constraints -sources clk_in -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/Clock_constraints true
set_ccopt_property target_insertion_delay -skew_group clk/Clock_constraints 1.000
set_ccopt_property extracted_from_clock_name -skew_group clk/Clock_constraints clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/Clock_constraints Clock_constraints
set_ccopt_property extracted_from_delay_corners -skew_group clk/Clock_constraints {SS FF}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

